create table if not exists invoice_settings (
  event_id bigint primary key references events(id) on delete cascade,
  invoice_number text not null default '',
  invoice_date text not null default '',
  due_date text not null default '',
  payment_terms text not null default 'Due on receipt',
  sender_name text not null default 'The Urban Slide',
  sender_address text not null default '',
  sender_email text not null default '',
  sender_phone text not null default '',
  bill_to_name text not null default '',
  bill_to_address text not null default '',
  remit_to text not null default '',
  notes text not null default '',
  logo_data_url text not null default ''
);

create table if not exists invoice_line_items (
  id bigint generated by default as identity primary key,
  event_id bigint not null references events(id) on delete cascade,
  description text not null default '',
  quantity numeric not null default 1,
  rate numeric not null default 0,
  sort_order integer not null default 0
);

alter table invoice_settings enable row level security;
alter table invoice_line_items enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'invoice_settings' and policyname = 'public full access invoice_settings'
  ) then
    create policy "public full access invoice_settings" on invoice_settings for all using (true) with check (true);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'invoice_line_items' and policyname = 'public full access invoice_line_items'
  ) then
    create policy "public full access invoice_line_items" on invoice_line_items for all using (true) with check (true);
  end if;
end $$;
