create table if not exists events (
  id bigint generated by default as identity primary key,
  name text not null default '',
  city text not null default '',
  state text not null default '',
  start_date text not null default '',
  end_date text not null default '',
  status text not null default 'Planning',
  contract_revenue numeric not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists event_info (
  event_id bigint primary key references events(id) on delete cascade,
  overview text not null default '',
  payment_schedule_notes text not null default '',
  meeting_location text not null default '',
  staffing_breakdown text not null default '',
  parking_notes text not null default '',
  water_usage_notes text not null default '',
  city_responsibilities text not null default '',
  weather_notes text not null default '',
  general_notes text not null default ''
);

create table if not exists revenue_items (
  id bigint generated by default as identity primary key,
  event_id bigint not null references events(id) on delete cascade,
  label text not null default '',
  amount numeric not null default 0,
  sort_order integer not null default 0
);

create table if not exists expense_items (
  id bigint generated by default as identity primary key,
  event_id bigint not null references events(id) on delete cascade,
  category text not null,
  label text not null default '',
  amount numeric not null default 0,
  notes text not null default '',
  sort_order integer not null default 0
);

create table if not exists payments (
  id bigint generated by default as identity primary key,
  event_id bigint not null references events(id) on delete cascade,
  description text not null default '',
  due_date text not null default '',
  amount_owed numeric not null default 0,
  amount_paid numeric not null default 0,
  paid_date text not null default '',
  check_number text not null default '',
  notes text not null default '',
  sort_order integer not null default 0
);

create table if not exists contacts (
  id bigint generated by default as identity primary key,
  event_id bigint not null references events(id) on delete cascade,
  name text not null default '',
  company text not null default '',
  role text not null default '',
  phone text not null default '',
  email text not null default '',
  quote_info text not null default '',
  notes text not null default '',
  sort_order integer not null default 0
);

create table if not exists todos (
  id bigint generated by default as identity primary key,
  event_id bigint not null references events(id) on delete cascade,
  task text not null default '',
  owner text not null default '',
  notes text not null default '',
  progress text not null default '',
  due_date text not null default '',
  completed boolean not null default false,
  sort_order integer not null default 0
);

create table if not exists flights (
  id bigint generated by default as identity primary key,
  event_id bigint not null references events(id) on delete cascade,
  trip_type text not null default '',
  person text not null default '',
  confirmation text not null default '',
  flight_time text not null default '',
  flight_date text not null default '',
  notes text not null default '',
  sort_order integer not null default 0
);

create table if not exists hotels (
  id bigint generated by default as identity primary key,
  event_id bigint not null references events(id) on delete cascade,
  date_label text not null default '',
  confirmation_number text not null default '',
  hotel_name text not null default '',
  notes text not null default '',
  sort_order integer not null default 0
);

create table if not exists rentals (
  id bigint generated by default as identity primary key,
  event_id bigint not null references events(id) on delete cascade,
  vendor text not null default '',
  drop_off_address text not null default '',
  mobile text not null default '',
  office text not null default '',
  confirmation text not null default '',
  email text not null default '',
  notes text not null default '',
  sort_order integer not null default 0
);

create table if not exists time_slots (
  id bigint generated by default as identity primary key,
  event_id bigint not null references events(id) on delete cascade,
  day_label text not null default '',
  headcount text not null default '',
  details text not null default '',
  hours text not null default '',
  notes text not null default '',
  sort_order integer not null default 0
);

create table if not exists staff (
  id bigint generated by default as identity primary key,
  event_id bigint not null references events(id) on delete cascade,
  name text not null default '',
  role text not null default '',
  email text not null default '',
  phone text not null default '',
  assigned_shift text not null default '',
  arrival_date text not null default '',
  departure_date text not null default '',
  flight_summary text not null default '',
  contract_status text not null default 'Not Sent',
  contract_due_date text not null default '',
  contract_notes text not null default '',
  invite_notes text not null default '',
  sort_order integer not null default 0
);

create table if not exists documents (
  id bigint generated by default as identity primary key,
  event_id bigint not null references events(id) on delete cascade,
  document_type text not null default '',
  original_name text not null default '',
  storage_path text not null default '',
  size bigint not null default 0,
  notes text not null default '',
  uploaded_at text not null default '',
  sort_order integer not null default 0
);

alter table events enable row level security;
alter table event_info enable row level security;
alter table revenue_items enable row level security;
alter table expense_items enable row level security;
alter table payments enable row level security;
alter table contacts enable row level security;
alter table todos enable row level security;
alter table flights enable row level security;
alter table hotels enable row level security;
alter table rentals enable row level security;
alter table time_slots enable row level security;
alter table staff enable row level security;
alter table documents enable row level security;

create policy "public full access events" on events for all using (true) with check (true);
create policy "public full access event_info" on event_info for all using (true) with check (true);
create policy "public full access revenue_items" on revenue_items for all using (true) with check (true);
create policy "public full access expense_items" on expense_items for all using (true) with check (true);
create policy "public full access payments" on payments for all using (true) with check (true);
create policy "public full access contacts" on contacts for all using (true) with check (true);
create policy "public full access todos" on todos for all using (true) with check (true);
create policy "public full access flights" on flights for all using (true) with check (true);
create policy "public full access hotels" on hotels for all using (true) with check (true);
create policy "public full access rentals" on rentals for all using (true) with check (true);
create policy "public full access time_slots" on time_slots for all using (true) with check (true);
create policy "public full access staff" on staff for all using (true) with check (true);
create policy "public full access documents" on documents for all using (true) with check (true);

insert into storage.buckets (id, name, public)
values ('event-documents', 'event-documents', true)
on conflict (id) do nothing;

create policy "public read event documents"
on storage.objects for select
using (bucket_id = 'event-documents');

create policy "public write event documents"
on storage.objects for insert
with check (bucket_id = 'event-documents');

create policy "public update event documents"
on storage.objects for update
using (bucket_id = 'event-documents')
with check (bucket_id = 'event-documents');

create policy "public delete event documents"
on storage.objects for delete
using (bucket_id = 'event-documents');
